Made the navber responsive by adding a hamburger menu
Heritians/Connecting-Villages pull request #75
Opened 2023-03-17 12:42 UTC by Vaibhav-shrivastav

fixes #70 (if any, otherwise delete this line), partly

# Description

* Added Hamburger menu for screen size <1023px,
* Made Navbar responsive using Bootstrap. 
* Added Shadow for navbar as whole

## Type of change

Note: Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New layer/algorithm
- [ ] Other (Specify)

## Tests

*  Tested by running locally using developer tools provided by chrome for various screen sizes as mentioned below,
     less than 767px
       Between 768px and 1023px
       More than 1024px

## Checklist

- [X] I have performed a self code_review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.

2023-03-17 12:57 UTC, mayureshagashe2105 commented
@Vaibhav-shrivastav, it seems like you have not pulled contributions made by other contributors which are causing conflicts with the main branch. Sync your fork and update your remote. Fix any conflicts that might occur. Thank you.

2023-03-17 13:22 UTC, Scholasticpal commented
@mayureshagashe2105 I have approved the changes.
Please re-review whether the changes you asked for have been made.

2023-03-17 13:37 UTC, mayureshagashe2105 commented
@itsksquare has triage access to this repo.  He will review your code shortly, thank you for your patience @Vaibhav-shrivastav.

2023-03-17 17:52 UTC, Vaibhav-shrivastav commented
@itsksquare I fixed the changes. For the Services dropdown part, I do not have the credentials to access login page, so that I can look at the exact problem. How should I get those credentials?

2023-03-18 19:19 UTC, Vaibhav-shrivastav commented
@itsksquare I have made the changes, just working on dropdown component for smaller screen sizes, I'll push them altogether.
Thank you!

2023-04-07 07:51 UTC, Vaibhav-shrivastav commented
@itsksquare I have made all the changes as you said, Could you check please?

2023-04-07 14:30 UTC, mayureshagashe2105 commented
@itsksquare once you approve the changes,  please squash and merge the feature branch.

2023-04-07 20:34 UTC, Scholasticpal commented
Hey @Vaibhav-shrivastav,

I have gone through your code changes and the navbar in mobile ratio looks nice with the hamburger icon!

A few important changes are needed that are missing here:

1. dropdown navbar doesn't display services when the screen width goes 360px. 
(The phone screens are smaller in width so the services tab won't open correctly on some phones. 
To check the same, try changing the width as shown in the ss attached)

2. dropdown gets covered when scrolling over the 'quotes carousel' on the home page.
(can try using the z-index CSS property to position the carousel behind the dropdown)

Please fix these issues so that we can merge your code quickly :)

![image](https://user-images.githubusercontent.com/80644106/230675164-4d62bb8b-5513-4a25-8bac-93ee4f126c65.png)

2023-04-08 04:35 UTC, Vaibhav-shrivastav commented
@Scholasticpal I have made the changes, could you re-review please?
Thank you for your patience!

2023-04-08 12:09 UTC, itsksquare requested changes
Hey @Vaibhav-shrivastav ,
The changes look fine, just some minor changes and cleanups before we can merge the code. Have a look at the comments in some of the files.

Thank you for your contributions!

2023-04-08 12:09 UTC, itsksquare commented on src/components/Dropdown/DropdownStyles.js
The position of the dropdown container can be set to absolute instead of fixed. Lines(10 - 11 & 16 - 20) can also be removed. This should fix the way the dropdown is displayed with respect to the services navlink.

2023-04-09 03:08 UTC, Vaibhav-shrivastav commented
@itsksquare I have updated the changes!

2023-04-09 04:49 UTC, itsksquare approved these changes
Hey @Vaibhav-shrivastav , thank you for your contributions, looks good to merge.

@Scholasticpal please squash merge these changes.

2023-04-09 06:42 UTC, Scholasticpal approved these changes

2023-04-09 06:49 UTC, merged